# Generated by Django 5.2.1 on 2025-06-12 05:15

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='sacred_name', unique=True),
        ),
    ]
