# Generated by Django 5.2.1 on 2025-06-09 06:13

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_category_about_category_main_heading_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_banner_img', models.FileField(blank=True, default=None, max_length=250, null=True, upload_to='banners')),
                ('Main_heading', models.CharField(blank=True, max_length=100, null=True)),
                ('short_description', tinymce.models.HTMLField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
            ],
        ),
    ]
