# Generated by Django 5.2.1 on 2025-06-23 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0009_alter_category_page_home_blog_shortdecription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category_page',
            old_name='home_blog_shortdecription',
            new_name='home_category_shortdecription',
        ),
        migrations.RenameField(
            model_name='category_page',
            old_name='home_blog_title',
            new_name='home_category_title',
        ),
    ]
