# Generated by Django 5.2.1 on 2025-06-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_img', models.FileField(blank=True, default=None, max_length=250, null=True, upload_to='banners')),
                ('logo_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
