# Generated by Django 5.2.1 on 2025-06-13 08:06

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutpage', '0003_ourmission_about_img_alt_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whytravel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_img', models.FileField(blank=True, default=None, max_length=250, null=True, upload_to='banners')),
                ('img_alt_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
            ],
        ),
    ]
