# Generated by Django 5.2.1 on 2025-06-23 11:42

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutpage', '0004_whytravel'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='banner_heading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='banner_short_description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ourmission',
            name='banner_heading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ourmission',
            name='banner_short_description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whytravel',
            name='banner_heading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='whytravel',
            name='banner_short_description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
