# Generated by Django 5.2.1 on 2025-06-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacredsite', '0006_alter_sacredsite_tripgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='sacredsite',
            name='courseduration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sacredsite',
            name='Accommodation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sacredsite',
            name='Besttime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sacredsite',
            name='Destination',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sacredsite',
            name='Meals',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sacredsite',
            name='MinGroupSize',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sacredsite',
            name='Style',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sacredsite',
            name='Total_Duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sacredsite',
            name='Transportation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sacredsite',
            name='TripGrade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
