# Generated by Django 5.2.1 on 2025-06-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacredsite', '0010_sacredsite_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sacredsite',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
