# Generated by Django 5.2.1 on 2025-06-18 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacredsite', '0016_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='sacredsite',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='sacredsite.sacredsite'),
            preserve_default=False,
        ),
    ]
