# Generated by Django 5.2.1 on 2025-06-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='location_address_link',
            field=models.CharField(blank=True, null=True),
        ),
    ]
