# Generated by Django 5.2.1 on 2025-06-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactpage', '0003_contact_telephone_number_first_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='location_address_link',
            new_name='country',
        ),
        migrations.AddField(
            model_name='contact',
            name='location_city',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='location_street',
            field=models.CharField(blank=True, null=True),
        ),
    ]
