# Generated by Django 5.2.1 on 2025-06-04 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_icon_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
