# Generated by Django 5.2.1 on 2025-06-06 08:52

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_icon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sacred_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='category_name', unique=True),
        ),
    ]
