# Generated by Django 5.2.1 on 2025-06-09 05:27

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_category_sacred_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='About',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='Main_heading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_banner_img',
            field=models.FileField(blank=True, default=None, max_length=250, null=True, upload_to='banners'),
        ),
        migrations.AddField(
            model_name='category',
            name='category_img',
            field=models.FileField(blank=True, default=None, max_length=250, null=True, upload_to='banners'),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='short_description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
