# Generated by Django 5.2.1 on 2025-06-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_img', models.FileField(blank=True, default=None, max_length=250, null=True, upload_to='banners')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
