# Generated by Django 5.2.1 on 2025-06-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactpage', '0002_contact_location_address_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='telephone_number_first',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='telephone_number_second',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
