# Generated by Django 5.2.1 on 2025-06-23 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactpage', '0004_rename_location_address_link_contact_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='telephone_number_first',
            new_name='whatsapp_number',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='telephone_number_second',
        ),
    ]
