# Generated by Django 5.2.1 on 2025-06-12 11:21

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
