# Generated by Django 5.2.1 on 2025-06-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacredsite', '0011_alter_sacredsite_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sacredsite',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
