# Generated by Django 5.2.1 on 2025-06-19 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sacredsite', '0019_alter_sacredsite_sacred_price'),
    ]

    operations = [
    ]
