# Generated by Django 5.2.1 on 2025-06-19 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sacredsite', '0020_auto_20250619_1155'),
    ]

    operations = [
    ]
