# Generated by Django 5.2.1 on 2025-06-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacredsite', '0025_remove_gallery_category_remove_gallery_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sacredpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_sacred_heading', models.CharField(blank='true', max_length=100, null='true')),
                ('home_sacred_shortdescription', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
