# Generated by Django 5.2.1 on 2025-06-12 05:31

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogg', '0002_blog_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='banner_img',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='sacredsite'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='blog_title', unique=True),
        ),
    ]
