# Generated by Django 5.2.1 on 2025-06-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogg', '0004_blog_img_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='banner_img_src',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogpages',
            name='home_heading_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
