# Generated by Django 5.2.1 on 2025-06-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogg', '0006_rename_home_heading_title_blogpages_home_blog_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpages',
            name='banner_img_src',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
