# Generated by Django 5.2.1 on 2025-06-05 09:13

import autoslug.fields
import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0003_alter_category_icon_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sacredsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sacred_image', models.FileField(default=None, max_length=250, null=True, upload_to='sacredsite')),
                ('sacred_name', models.CharField(max_length=100)),
                ('sacred_desc', tinymce.models.HTMLField(blank=True, null=True)),
                ('sacred_location', models.CharField(max_length=100)),
                ('sacred_price', models.CharField(max_length=50)),
                ('sacred_days', models.CharField(blank=True, max_length=50, null=True)),
                ('banner_image', models.FileField(blank=True, default=None, max_length=250, null=True, upload_to='banners')),
                ('Destination', models.CharField(max_length=100)),
                ('Total_Duration', models.CharField(max_length=100)),
                ('Besttime', models.CharField(max_length=100)),
                ('TripGrade', models.CharField(max_length=100)),
                ('Transportation', models.CharField(max_length=100)),
                ('Accommodation', models.CharField(max_length=100)),
                ('Style', models.CharField(max_length=100)),
                ('Meals', models.CharField(max_length=100)),
                ('MinGroupSize', models.CharField(max_length=100)),
                ('overview', tinymce.models.HTMLField()),
                ('include', tinymce.models.HTMLField()),
                ('exclude', tinymce.models.HTMLField()),
                ('sitemap', models.CharField(blank=True, null=True)),
                ('sacred_slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='sacred_name', unique=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sacredsite', to='category.category')),
            ],
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_title', models.CharField(max_length=255)),
                ('description', tinymce.models.HTMLField()),
                ('sacredsite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='sacredsite.sacredsite')),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('sacredsite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='sacredsite.sacredsite')),
            ],
        ),
        migrations.CreateModel(
            name='Discounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberofpeople', models.CharField(max_length=255)),
                ('price', models.TextField()),
                ('sacredsite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='sacredsite.sacredsite')),
            ],
        ),
    ]
