# Generated by Django 5.2.1 on 2025-06-17 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacredsite', '0013_tourbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourbooking',
            name='is_confirmed',
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sacredsite.sacredsite'),
        ),
    ]
