# Generated by Django 5.2.1 on 2025-06-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacredsite', '0014_remove_tourbooking_is_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourbooking',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
