# Generated by Django 5.2.1 on 2025-06-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacredsite', '0018_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sacredsite',
            name='sacred_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Base Price per person', max_digits=10, null=True),
        ),
    ]
