# Generated by Django 5.2.1 on 2025-06-22 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sacredsite', '0024_sacredsite_sacred_img_src'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='category',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='title',
        ),
    ]
