# Generated by Django 5.2.1 on 2025-06-11 11:44

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_img', models.FileField(default=None, max_length=250, null=True, upload_to='sacredsite')),
                ('blog_title', models.CharField(max_length=200)),
                ('blog_description', tinymce.models.HTMLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blogpages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.FileField(default=None, max_length=250, null=True, upload_to='sacredsite')),
                ('main_heading', models.CharField(blank=True, max_length=100, null=True)),
                ('short_description', tinymce.models.HTMLField(blank=True, null=True)),
                ('second_heading', models.CharField(blank=True, max_length=100, null=True)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
            ],
        ),
    ]
