# Generated by Django 5.2.1 on 2025-06-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogg', '0003_blog_banner_img_alter_blog_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='img_src',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
