# Generated by Django 5.2.1 on 2025-06-23 07:55

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogg', '0005_blog_banner_img_src_blogpages_home_heading_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpages',
            old_name='home_heading_title',
            new_name='home_blog_title',
        ),
        migrations.AddField(
            model_name='blogpages',
            name='home_blog_description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
