# Generated by Django 5.2.1 on 2025-06-17 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_subsciptionform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubsciptionForm',
        ),
    ]
