# Generated by Django 5.2.1 on 2025-06-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_img', models.FileField(blank=True, default=None, max_length=250, null=True, upload_to='banners')),
                ('h1_Name', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=100)),
            ],
        ),
    ]
