# Generated by Django 5.2.1 on 2025-06-13 05:07

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_commitment_remove_home_commitment_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Short_description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, default=None, max_length=250, null=True, upload_to='banners')),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
            ],
        ),
    ]
