# Generated by Django 5.2.1 on 2025-06-12 11:39

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutpage', '0002_alter_about_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ourmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_img', models.FileField(blank=True, default=None, max_length=250, null=True, upload_to='banners')),
                ('img_alt_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='about',
            name='img_alt_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
