# Generated by Django 5.2.1 on 2025-06-09 11:27

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_home_commitment_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commitment_heading', models.CharField(blank=True, max_length=100, null=True)),
                ('commitment_description', tinymce.models.HTMLField(blank=True, null=True)),
                ('commitment_img', models.FileField(default=None, max_length=250, null=True, upload_to='sacredsite')),
            ],
        ),
        migrations.RemoveField(
            model_name='home',
            name='commitment_description',
        ),
        migrations.RemoveField(
            model_name='home',
            name='commitment_heading',
        ),
        migrations.RemoveField(
            model_name='home',
            name='commitment_img',
        ),
    ]
