# Generated by Django 5.2.1 on 2025-06-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacredsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sacredsite',
            name='src_bannerimage',
            field=models.CharField(blank=True, null=True),
        ),
    ]
