# Generated by Django 5.2.1 on 2025-06-06 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacredsite', '0003_alter_sacredsite_tripgrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sacredsite',
            name='TripGrade',
            field=models.CharField(blank=True, default=1, max_length=100),
            preserve_default=False,
        ),
    ]
