# Generated by Django 5.2.1 on 2025-06-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacredsite', '0005_alter_sacredsite_tripgrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sacredsite',
            name='TripGrade',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
