# Generated by Django 5.2.1 on 2025-06-06 07:47

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacredsite', '0008_alter_discounts_numberofpeople_alter_discounts_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='day_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sacredsite',
            name='exclude',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sacredsite',
            name='include',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
