# Generated by Django 5.2.1 on 2025-06-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacredsite', '0021_auto_20250619_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sacredsite',
            name='sacred_price',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
