# Generated by Django 5.2.1 on 2025-06-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacredsite', '0009_alter_itinerary_day_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sacredsite',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
