# Generated by Django 5.2.1 on 2025-06-18 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacredsite', '0017_gallery_sacredsite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_participants', models.PositiveIntegerField(help_text='Minimum number of participants for this discount')),
                ('max_participants', models.PositiveIntegerField(blank=True, help_text='Maximum number of participants for this discount (leave blank for no limit)', null=True)),
                ('discount_per_pax', models.DecimalField(decimal_places=2, help_text='Discount amount per participant', max_digits=10)),
                ('discount_type', models.CharField(choices=[('percent', 'Percentage'), ('fixed', 'Fixed Amount')], default='fixed', help_text='Type of discount to apply', max_length=10)),
                ('sacredsite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount', to='sacredsite.sacredsite')),
            ],
        ),
    ]
