# Generated by Django 5.2.1 on 2025-06-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacredsite', '0023_gallery_category_gallery_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='sacredsite',
            name='sacred_img_src',
            field=models.CharField(blank='true', max_length=100, null='true'),
            preserve_default='true',
        ),
    ]
