# Generated by Django 5.2.1 on 2025-06-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_category_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='home_blog_shortdecription',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='home_blog_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
