# Generated by Django 5.2.1 on 2025-06-23 07:14

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_remove_category_home_blog_shortdecription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_page',
            name='home_blog_shortdecription',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
