# Generated by Django 5.2.1 on 2025-06-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_slug', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=70)),
                ('description', models.CharField(max_length=160)),
                ('canonical', models.URLField(blank=True, null=True)),
                ('og_title', models.CharField(max_length=70)),
                ('og_description', models.CharField(max_length=300)),
                ('og_image', models.URLField(blank=True, null=True)),
                ('og_type', models.CharField(default='website', max_length=20)),
            ],
        ),
    ]
